ASP.NET.MVC5.Client/Models/EquipmentViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASP.NET.MVC5.Client.Models
{
    public class EquipmentViewModels
    {
    }
    public class EquipmentItemViewModel
    {
        public string Id { get; set; }
        public string DepartmentName { get; set; }
        public string Name { get; set; }
        public string EquipmentModel { get; set; }
        public string CreationDate { get; set; }
        public string Description { get; set; } 
    }


    public class EquipmentListViewModel
    {
        public int Total { get; set; }
        public IEnumerable<EquipmentItemViewModel> Equipment { get; set; } 
    }

    public class EquipmentCreateViewModel
    {

        public string Id { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [Display(Name = "Equipment Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Model")]
        public string EquipmentModel { get; set; }

         [Required]
         [Display(Name = "Department Name")]
        public string DepartmentId { get; set; }
        public IEnumerable<SelectListItem> FacilitiesModel  { get; set; } 

        [Required]
        [Display(Name = "Description")]
        public string Description { get; set; }
    }


     
}

ASP.NET.MVC5.Client/Controllers/EquipmentController.cs
using Application.BoundedConext.StoreModule;
using ASP.NET.MVC5.Client.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ASP.NET.MVC5.Client.Extensions;
using Application.BoundedConext.ERPModule;

namespace ASP.NET.MVC5.Client.Controllers
{
    public class EquipmentController : Controller
    {

        private IEquipmentAggregateManagementService _equipmentAggregateManagementService;
        private IDepartmentAggregateManagementService _departmentAggregateManagementService;
        public EquipmentController(IEquipmentAggregateManagementService equipmentAggregateManagementService, IDepartmentAggregateManagementService departmentAggregateManagementService)
        {
            if (equipmentAggregateManagementService == (IEquipmentAggregateManagementService)null)
                throw new ArgumentNullException("organizationManagementService");
            if (departmentAggregateManagementService == (IDepartmentAggregateManagementService)null)
                throw new ArgumentNullException("departmentAggregateManagementService");
            _equipmentAggregateManagementService = equipmentAggregateManagementService;
            _departmentAggregateManagementService = departmentAggregateManagementService;


        }
        // GET: Equipment
        public async Task<ActionResult> Index()
        {


            var model = await _equipmentAggregateManagementService.GetAllEquipmentAsync();
            return View(model.ToViewModel());
        }

        // GET: Equipment/Details/5
        public ActionResult Details(int id)
        {

            return View();
        }

        // GET: Equipment/Create
        public async Task<ActionResult> Create()
        {
            try
            {
                EquipmentCreateViewModel model = new EquipmentCreateViewModel();
                var fmodel = await _departmentAggregateManagementService.GetAllDepartmentsAsync();
                if (fmodel != null)
                {
                    model.FacilitiesModel = fmodel.Select(x => new SelectListItem()
                    {
                        Value = x.Id.ToString() + "#$#" + x.Name.Replace(" ","#+#"),
                        Text = x.Name
                    });
                }

                return View(model);
            }
            catch
            {
                return View();
            }
        }

        // POST: Equipment/Create
        [HttpPost]
        public async Task<ActionResult> Create(EquipmentCreateViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var equip = model.ToModel();
                    await this._equipmentAggregateManagementService.AddEquipmentAsync(equip);
                    return RedirectToAction("Index");
                }

                return View(model);
                // TODO: Add insert logic here
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Equipment/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Equipment/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Equipment/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Equipment/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ASP.NET.MVC5.Client/Views/Equipment/Create.cshtml
@model ASP.NET.MVC5.Client.Models.EquipmentCreateViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Create equipment</h2>



@using (Html.BeginForm("Create", "Equipment", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.EquipmentModel, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.EquipmentModel, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.DepartmentId, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.DepartmentId, Model.FacilitiesModel, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
        </div>
    </div>
}

ASP.NET.MVC5.Client/Views/Equipment/Index.cshtml
@model ASP.NET.MVC5.Client.Models.EquipmentListViewModel
@{
    ViewBag.Title = "Index";
}

<h2>All equipment</h2>
@Html.ActionLink("Create", "Create", "Equipment", new { @class = "btn btn-primary btn-lg pull-right" })
<p><strong>Total : </strong>@Model.Total</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Equipment Name</th>
            <th>Department Name</th>
            <th>Model</th>
            <th>Creation date</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var f in @Model.Equipment)
        {
            <tr>
                <td scope="row">@f.Id</td>
                <td>@f.Name</td>
                <td>@f.DepartmentName</td>
                <td>@f.EquipmentModel</td>
                <td>@f.CreationDate</td>
                <td>@f.Description</td>
            </tr>
        }
    </tbody>
</table>