ASP.NET.MVC5.Client/Models/FacilityViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ASP.NET.MVC5.Client.Models
{
    public class FacilityViewModels
    {
    }

    public class FacilityItelViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
    }


    public class FacilityListViewModel
    {
        public int Total { get; set; }
        public IEnumerable<FacilityItelViewModel> Facilities { get; set; }
    }

    public class FacilityCreateViewModel
    {

        public string Id { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [Display(Name = "Facility Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Facility Address")]
        public string Address { get; set; }

        [Required]
        [Display(Name = "City")]
        public string City { get; set; }

        [Required]
        [Display(Name = "Zip Code")]
        public string ZipCode { get; set; }
    }
}

ASP.NET.MVC5.Client/Controllers/FacilityController.cs
using Application.BoundedConext.ERPModule;
using ASP.NET.MVC5.Client.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ASP.NET.MVC5.Client.Extensions;

namespace ASP.NET.MVC5.Client.Controllers
{
    public class FacilityController : Controller
    {
        private IOrganizationManagementService _organizationManagementService;
        public FacilityController(IOrganizationManagementService organizationManagementService)
        {
            if (organizationManagementService == (IOrganizationManagementService)null)
                throw new ArgumentNullException("organizationManagementService");
            _organizationManagementService = organizationManagementService;

        }

        // GET: Facility
        public async Task<ActionResult> Index()
        {

            var model = await _organizationManagementService.GetAllFacilitiesAsync();
            return View(model.ToViewModel());
        }

        // GET: Facility/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Facility/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Facility/Create
        [HttpPost]
        public async Task<ActionResult> Create(FacilityCreateViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var org = model.ToModel();
                    await _organizationManagementService.AddAsync(org);
                    return RedirectToAction("Index");
                }

                return View(model);
                // TODO: Add insert logic here
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Facility/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Facility/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Facility/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Facility/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ASP.NET.MVC5.Client/Views/Facility/Create.cshtml
@model ASP.NET.MVC5.Client.Models.FacilityCreateViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Create facility</h2>

 

@using (Html.BeginForm("Create", "Facility", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Address, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.City, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ZipCode, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.ZipCode, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
        </div>
    </div>
}

ASP.NET.MVC5.Client/Views/Facility/Index.cshtml
@model ASP.NET.MVC5.Client.Models.FacilityListViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Facilities</h2>
@Html.ActionLink("Create", "Create", "facility", new { @class = "btn btn-primary btn-lg pull-right",id="facilityCreate" })
<p><strong>Total : </strong>@Model.Total</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Facility Name</th>
            <th>Facility Address</th>
            <th>Facility City</th>
            <th>Facility Zip code</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var f in @Model.Facilities)
        {
            <tr>
                <th scope="row">@f.Id</th>
                <td>@f.Name</td>
                <td>@f.Address</td>
                <td>@f.City</td>
                <td>@f.ZipCode</td>
            </tr>
        }
    </tbody>
</table>